swagger: '2.0'
info:
  description: >-
    Describes various endpoints for Tree Survey.
  version: 1.0.0
  title: Tree Survey
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8080
basePath: /api/v1
tags:
  - name: Tree Survey
    description: An API to perform basic CRUD operations
  
schemes:
  - https
  - http
paths:
  /surveys:
    get:
      tags:
        - Get all survey details
      summary: Get all surveys with details
      description: Retrieves all survey details
      operationId: getSurveys
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              surveyArray:
                type: array            
                items:
                  $ref: '#/definitions/Survey'
        '400':
          description: Invalid status value
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
  
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Survey:
    type: object
    required:
      - name
      - photoUrls
    properties:
      treeId:
        type: string
        description: Unique identifier for each Tree
      species:
        type: string
        description: Type or Family of Tree
      experiment:
        type: string
        description: Nature of experiment conducted
      site:
        type: string
        description: Location where experiment was carried out
      surveyor:
        type: string
        description: Person who conducted this experiment
      location:
        type: string
        description: Place of experiment
      plantingDate:
        type: string
        description: Date of Plantation
      inspectionDate:
        type: string
        description: Date of Inspection
      typeOfTreatment:
        type: string
        description: Nature of treatment for the plant
      healthScore:
        type: integer
        format: int64
        description: Rating regarding health of plant
      pathogenFound:
        type: string
        description: was any infection found ?
      woodBorerFound:
        type: string
        description: were any wood borer bettle infections found ?
      notes:
        type: string
        description: Observations and comments go here
      
    xml:
      name: Pet
  
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
